social/messanger/urls.py
from django.urls import path

from .views import *

app_name = 'messanger'

urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('chat/', chat_list, name='chats'),
	path('chat-view/<int:user>/<int:with_user>', chat_view, name='chat')
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from messanger.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messanger.urls')),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

social/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
	path('registration/', RegistrationView.as_view(), name='reg'),
	path('login/', LoginUserView.as_view(), name='login'),
	path('logout/', user_logout, name='user_logout'),
	path('profile/<int:pk>/', user_profile, name='profile'),
	path('add-friend/<int:senter_id>/<int:accepter_id>/', accept_friend, name='accept_friend'),
	path('reject-friend-request/<int:senter_id>/<int:accepter_id>/', reject_friend, name='reject_friend'),
	path('create-request-friends/<int:senter_id>/<int:accept_id>/', create_request_friends, name='create_request_friends'),
	path('delete-friend/<int:owner_id>/<int:friend_id>', delete_friend, name='delete_friend'),
	path('friend-list/<int:pk>/', check_friend_list, name='friend_list'),
	path('post-handler/<int:pk>/<int:user_id>/', post_handler, name='post_handler')
]

social/messanger/models.py
from django.db import models
from django.utils import timezone

from users.models import User

# Create your models here.
class Chat(models.Model):
	user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
	with_user = models.ForeignKey(User, related_name='chat_with', on_delete=models.CASCADE)


class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	chat = models.ForeignKey(Chat, related_name='msg', on_delete=models.CASCADE)
	text = models.TextField()
	date = models.DateTimeField(default=timezone.now)

social/messanger/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from users.models import User
from .models import Chat, Message

# Create your views here.
class IndexView(TemplateView):
	template_name = 'messanger/index.html'


def chat_list(request):

	context = {}

	if request.method == 'GET':
		if 'add_new_chat' in request.GET:
				with_user = request.GET.get('with_user')

				if len(Chat.objects.filter(user_id=request.user.id).filter(with_user_id=with_user).all()) >= 1:
					context['error'] = 'Диалог с данным пользователем уже есть.'
				else:
					c = Chat(
						user = request.user,
						with_user = User.objects.get(pk=with_user)
					)
					c2 = Chat(
						user=User.objects.get(pk=with_user),
						with_user=request.user
					)
					c.save()
					c2.save()
					return HttpResponseRedirect(reverse('messanger:chats'))

		elif 'user' in request.GET and 'with_user' in request.GET:
			user = request.GET.get('user')
			with_user = request.GET.get('with_user')

			Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first().delete()
			Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first().delete()

			return HttpResponseRedirect(reverse('messanger:chats'))


	if len(Chat.objects.filter(user_id=request.user.id).all()) >= 1:
		context['chats'] = Chat.objects.filter(user_id=request.user.id).all()
		context['chats_with_id'] = []

		for chat in context['chats']:
			context['chats_with_id'].append(chat.with_user.id)

		print(context['chats_with_id'])

	else:
		context['chats'] = []

	return render(request, 'messanger/chat_list.html', context=context)


def chat_view(request, user, with_user):
	context = {}
	context['chat'] = Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first()
	context['with_user_dialog'] = User.objects.get(pk=with_user)

	if request.method == 'POST':
		if 'msg_text' in request.POST:
			msg1 = Message(
				user=request.user,
				chat=context['chat'],
				text=request.POST.get('msg_text')
			)
			msg1.save()

			msg2 = Message(
				user=request.user,
				chat=Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first(),
				text=request.POST.get('msg_text')
			)
			msg2.save()

	return render(request, 'messanger/chat.html', context=context)

social/messanger/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Social</title>


  <style>
      #zatemnenie {
        background: rgba(102, 102, 102, 0.5);
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        display: none;
      }
      #okno {
        width: 600px;
        height: 600px;
        text-align: center;
        padding: 15px;
        border: 3px gray;
        border-radius: 2px;
        color: black;
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        margin: auto;
        background: #fff;
      }
      #zatemnenie:target {display: block;}
      .close {

        padding: 0 12px;
        text-decoration: none;
        background: #fff;
        font-size: 14pt;
        cursor:pointer;
        float: right;
      }
    </style>


  
	<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
	
	<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

</head>
<body style="background: #B5F2EA;">
<div class='container'>
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'messanger:index'%}">Social</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Друзья
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          	<li>
          		<a class='dropdown-item' href="{% url 'users:friend_list' user.id%}">Список друзей</a>
          	</li>
          	<li>
          		<a class='dropdown-item' href="{% url 'users:friend_list' user.id%}">Найти человека
          		</a>
          	</li>
            {%if user.accept%}
            	{%for req in user.accept.all%}
            		<li>
            		<hr>
            		<p class="dropdown-item">
            			Запрос в друзья от {{req.user_send.username}}<br>
            			<a class="btn btn-outline-success" href="{% url 'users:accept_friend' req.user_send.id user.id%} ">Принять</a><a class='btn btn-outline-danger' href="{%url 'users:reject_friend' req.user_send.id user.id%}"> Отклонить</a>
            		</p>            		
            		</li>
            		<hr>
            	{%endfor%}
            {%endif%}
            
            <!-- <li><a class="dropdown-item" href="#">Другое действие</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Что-то еще здесь</a></li> -->
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'messanger:chats' %}">Сообщения</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Отключенная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:profile' user.id %}">{{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:user_logout' %}">Выйти</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

	{% block content %}
	{% endblock %}
{%else%}
<div class="container" style="text-align: center;">
	<p>
		<h1>Social</h1>
		<h4>
			Лучшая социальная сеть на данный момент и в будующем.
		</h4>
	</p>

	<p>
		<a href="{%url 'users:reg'%}" class="btn btn-outline-info btn-lg" style="margin-right: 20px;">Регистрация</a>
		<a href="{% url 'users:login' %}" class="btn btn-outline-info btn-lg">Авторизация</a>
	</p>
	
</div>
{%endif%}
</div>

</body>
</html>