messanger/urls.py
from django.urls import path

from .views import *

app_name = 'messanger'

urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('chat/', chat_list, name='chats'),
	path('chat-view/<int:user>/<int:with_user>', chat_view, name='chat'),
	path('delete-message/', delete_msg, name='delete_msg')
]

messanger/models.py
from django.db import models
from django.utils import timezone

from users.models import User

# Create your models here.

class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.TextField()
	date = models.DateTimeField(default=timezone.now)


class Chat(models.Model):
	users = models.ManyToManyField(User)
	messages = models.ManyToManyField(Message)

messanger/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from users.models import User
from .models import Chat, Message

# Create your views here.
class IndexView(TemplateView):
	template_name = 'messanger/index.html'


def chat_list(request):

	context = {}

	if request.method == 'GET':
		if 'add_new_chat' in request.GET:
				with_user_id = request.GET.get('with_user')
				with_user = User.objects.get(pk=with_user_id)

				if len(Chat.objects.filter(users__id=request.user.id).filter(users__id=with_user_id).all()) >= 1:
					context['error'] = 'Диалог с данным пользователем уже есть.'
				else:

					c = Chat()
					c.save()
					c.users.add(request.user, with_user)
					c.save()

					return HttpResponseRedirect(reverse('messanger:chats'))

		elif 'user' in request.GET and 'with_user' in request.GET:
			user = request.GET.get('user')
			with_user = request.GET.get('with_user')

			if int(user) == request.user.id:
				Chat.objects.filter(users__id=user).filter(users__id=with_user).delete()

			return HttpResponseRedirect(reverse('messanger:chats'))


	if len(Chat.objects.filter(users__id=request.user.id).all()) >= 1:
		context['chats'] = Chat.objects.filter(users__id=request.user.id).all()
		context['chats_with_id'] = []

		for chat in context['chats']:
			
			for user in chat.users.all():
				if user.username == request.user.username:
					continue
				else:
					context['chats_with_id'].append(user.id)

	else:
		context['chats'] = ''


	return render(request, 'messanger/chat_list.html', context=context)


def chat_view(request, user, with_user):
	context = {}
	context['chat'] = Chat.objects.filter(users__id=user).filter(users__id=with_user).first()
	context['with_user_dialog'] = User.objects.get(pk=with_user)

	if request.method == 'POST':
		if 'msg_text' in request.POST:
			c=Chat.objects.filter(users__id=user).filter(users__id=with_user).first()
			
			msg = Message(
				user=request.user,
				text=request.POST.get('msg_text')
			)
			msg.save()

			c.messages.add(msg)
			c.save()
			

	return render(request, 'messanger/chat.html', context=context)


def delete_msg(request):

	if request.method == 'GET':

		user_id = request.GET.get('user_id')
		with_user_id = request.GET.get('with_user_id')
		message_id = request.GET.get('message_id')

		if request.user.id == int(user_id):
			mc = Chat.objects.filter(messages__pk=message_id).first()
			m = mc.messages.get(pk=message_id).delete()


	return HttpResponseRedirect(reverse('messanger:chat', 
		kwargs={'user': user_id, 
				'with_user': with_user_id
				}
	))

messanger/templates/messanger/chat.html
{% extends 'base.html' %}
{%block content%}

	<div class="container" style="background: #DEF7FE;">
		<h4>{{with_user_dialog.username}}</h4>
		<hr>
		<div style="background: whitesmoke;">
		{%for message in chat.messages.all%}
			<p>
				{{message.user.username}}: <br>
				{{message.text}} <br> отправлено {{message.date}} 
				{% if message.user.id == user.id %}
				<a href="{% url 'messanger:delete_msg' %}?user_id={{user.id}}&with_user_id={{with_user_dialog.id}}&message_id={{message.id}}">
					Удалить сообщение
				</a>
				{% endif %}
			</p>
		{%empty%}
		<h5>Сообщений пока что нет.</h5>
		{%endfor%}
		</div>
		<hr>
		<form action="{% url 'messanger:chat' user.id with_user_dialog.id %}#new_msg" method='post' id="new_msg">
			{% csrf_token %}
			<textarea name='msg_text' rows="1" cols="40" placeholder="Ваше сообщение"></textarea><input type="submit" class="btn btn-outline-success" style="font-size: 13px;" name="">
			
		</form>
	</div>

{%endblock%}

messanger/templates/messanger/chat_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="background: #DEF7FE;">

	<h1>Ваши диалоги</h1>

	<hr>

		<div id="zatemnenie">
	      <div id="okno">
	      	<a href="#" class="close" style="">❌</a>
	        <h4>Выберите пользователя для начала диалога</h5>
	        {%if error%}
	        	<p>{{error}}</p>
	        {%endif%}

	        

	        {%for friend in user.owner.all%}
	        {% if friend.friend.id in chats_with_id %}
	        {%else%}
	        <hr>
	        <div>
	        	<h5 style="text-align: left;">{{friend.friend.username}} | {{friend.friend.get_full_name}}<br><a style="margin-top: 10px;font-size: 14px;" class="btn btn-outline-success" href="{% url 'messanger:chats' %}?add_new_chat=yes&with_user={{friend.friend.id}}">Начать</a></h5>
	        </div>
	        <hr>
	        {%endif%}
	        {% endfor %}
	      </div>
	    </div>

	<a style="margin: 20px;" class="btn btn-outline-info"  href="#zatemnenie">Новый диалог c другом</a>
	<hr>

	{% if chats %}
	{% for chat in chats %}
	{%for user_dialog in chat.users.all%}
	{% if  user_dialog.id != user.id%}
		<h3>
			{{ user_dialog.username }}
			<a class="btn btn-outline-success" href="{% url 'messanger:chat' user.id user_dialog.id %}#new_msg">Открыть диалог</a>
			<a class="btn btn-outline-danger" href="{% url 'messanger:chats' %}?user={{user.id}}&with_user={{user_dialog.id}}">Удалить диалог</a>
			<hr>
		</h3>
		{% else %}
		{%endif%}
		{%endfor%}
	{%empty%}
	<h3>У вас пока нет ни одного диалога, но вы можете начать его прямо сейчас</h3>
	{%endfor%}
	{%endif%}


</div>
{% endblock %}