social/messanger/urls.py
from django.urls import path

from .views import *

app_name = 'messanger'

urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('chat/', chat_list, name='chats'),
	path('chat-view/<int:user>/<int:with_user>', chat_view, name='chat')
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from messanger.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messanger.urls')),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

social/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
	path('registration/', RegistrationView.as_view(), name='reg'),
	path('login/', LoginUserView.as_view(), name='login'),
	path('logout/', user_logout, name='user_logout'),
	path('profile/<int:pk>/', user_profile, name='profile'),
	path('add-friend/<int:senter_id>/<int:accepter_id>/', accept_friend, name='accept_friend'),
	path('reject-friend-request/<int:senter_id>/<int:accepter_id>/', reject_friend, name='reject_friend'),
	path('create-request-friends/<int:senter_id>/<int:accept_id>/', create_request_friends, name='create_request_friends'),
	path('delete-friend/<int:owner_id>/<int:friend_id>', delete_friend, name='delete_friend'),
	path('friend-list/<int:pk>/', check_friend_list, name='friend_list'),
	path('post-handler/<int:pk>/<int:user_id>/', post_handler, name='post_handler')
]

social/messanger/models.py
from django.db import models
from django.utils import timezone

from users.models import User

# Create your models here.
class Chat(models.Model):
	user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
	with_user = models.ForeignKey(User, related_name='chat_with', on_delete=models.CASCADE)


class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	chat = models.ForeignKey(Chat, related_name='msg', on_delete=models.CASCADE)
	text = models.TextField()
	date = models.DateTimeField(default=timezone.now)

social/messanger/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from users.models import User
from .models import Chat, Message

# Create your views here.
class IndexView(TemplateView):
	template_name = 'messanger/index.html'


def chat_list(request):

	context = {}

	if request.method == 'GET':
		if 'add_new_chat' in request.GET:
				with_user = request.GET.get('with_user')

				if len(Chat.objects.filter(user_id=request.user.id).filter(with_user_id=with_user).all()) >= 1:
					context['error'] = 'Диалог с данным пользователем уже есть.'
				else:
					c = Chat(
						user = request.user,
						with_user = User.objects.get(pk=with_user)
					)
					c2 = Chat(
						user=User.objects.get(pk=with_user),
						with_user=request.user
					)
					c.save()
					c2.save()
					return HttpResponseRedirect(reverse('messanger:chats'))

		elif 'user' in request.GET and 'with_user' in request.GET:
			user = request.GET.get('user')
			with_user = request.GET.get('with_user')

			Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first().delete()
			Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first().delete()

			return HttpResponseRedirect(reverse('messanger:chats'))


	if len(Chat.objects.filter(user_id=request.user.id).all()) >= 1:
		context['chats'] = Chat.objects.filter(user_id=request.user.id).all()
		context['chats_with_id'] = []

		for chat in context['chats']:
			context['chats_with_id'].append(chat.with_user.id)

		print(context['chats_with_id'])

	else:
		context['chats'] = []

	return render(request, 'messanger/chat_list.html', context=context)


def chat_view(request, user, with_user):
	context = {}
	context['chat'] = Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first()
	context['with_user_dialog'] = User.objects.get(pk=with_user)

	if request.method == 'POST':
		if 'msg_text' in request.POST:
			msg1 = Message(
				user=request.user,
				chat=context['chat'],
				text=request.POST.get('msg_text')
			)
			msg1.save()

			msg2 = Message(
				user=request.user,
				chat=Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first(),
				text=request.POST.get('msg_text')
			)
			msg2.save()

	return render(request, 'messanger/chat.html', context=context)

social/messanger/templates/messanger/chat.html
{% extends 'base.html' %}
{%block content%}

	<div class="container" style="background: #DEF7FE;">
		<h4>{{with_user_dialog.username}}</h4>
		<hr>
		<div style="background: whitesmoke;">
		{%for message in chat.msg.all%}
			<p>
				{{message.user.username}}: <br>
				{{message.text}} <br> отправлено {{message.date}} 
			</p>
		{%empty%}
		<h5>Сообщений пока что нет.</h5>
		{%endfor%}
		</div>
		<hr>
		<form action="{% url 'messanger:chat' user.id with_user_dialog.id %}#new_msg" method='post' id="new_msg">
			{% csrf_token %}
			<textarea name='msg_text' rows="1" cols="40" placeholder="Ваше сообщение"></textarea><input type="submit" class="btn btn-outline-success" style="font-size: 13px;" name="">
			
		</form>
	</div>

{%endblock%}

social/messanger/templates/messanger/chat_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="background: #DEF7FE;">

	<h1>Ваши диалоги</h1>

	<hr>

		<div id="zatemnenie">
	      <div id="okno">
	      	<a href="#" class="close" style="">❌</a>
	        <h4>Выберите пользователя для начала диалога</h5>
	        {%if error%}
	        	<p>{{error}}</p>
	        {%endif%}
	        {%for friend in user.owner.all%}
	        {% if friend.friend.id in chats_with_id %}
	        {%else%}
	        <hr>
	        <div>
	        	<h5 style="text-align: left;">{{friend.friend.username}} | {{friend.friend.get_full_name}}<br><a style="margin-top: 10px;font-size: 14px;" class="btn btn-outline-success" href="{% url 'messanger:chats' %}?add_new_chat=yes&with_user={{friend.friend.id}}">Начать</a></h5>
	        </div>
	        <hr>
	        {%endif%}
	        {% endfor %}
	      </div>
	    </div>

	<a style="margin: 20px;" class="btn btn-outline-info"  href="#zatemnenie">Новый диалог c другом</a>
	<hr>

	{% if chats %}
	{% for chat in chats %}
		<h3>
			{{ chat.with_user.username }}
			<a class="btn btn-outline-success" href="{% url 'messanger:chat' user.id chat.with_user.id %}#new_msg">Открыть диалог</a>
			<a class="btn btn-outline-danger" href="{% url 'messanger:chats' %}?user={{user.id}}&with_user={{chat.with_user.id}}">Удалить диалог</a>
			<hr>
		</h3>
	{%empty%}
	<h3>У вас пока нет ни одного диалога, но вы можете начать его прямо сейчас</h3>
	{%endfor%}
	{%endif%}


</div>
{% endblock %}

social/messanger/templates/messanger/index.html
{% extends 'base.html' %}
{%block content%}


{%endblock%}