social/messanger/urls.py
from django.urls import path

from .views import *

app_name = 'messanger'

urlpatterns = [
	path('', IndexView.as_view(), name='index'),
	path('chat/', chat_list, name='chats'),
	path('chat-view/<int:user>/<int:with_user>', chat_view, name='chat')
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from messanger.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messanger.urls')),
    path('users/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

social/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
	path('registration/', RegistrationView.as_view(), name='reg'),
	path('login/', LoginUserView.as_view(), name='login'),
	path('logout/', user_logout, name='user_logout'),
	path('profile/<int:pk>/', user_profile, name='profile'),
	path('add-friend/<int:senter_id>/<int:accepter_id>/', accept_friend, name='accept_friend'),
	path('reject-friend-request/<int:senter_id>/<int:accepter_id>/', reject_friend, name='reject_friend'),
	path('create-request-friends/<int:senter_id>/<int:accept_id>/', create_request_friends, name='create_request_friends'),
	path('delete-friend/<int:owner_id>/<int:friend_id>', delete_friend, name='delete_friend'),
	path('friend-list/<int:pk>/', check_friend_list, name='friend_list'),
	path('post-handler/<int:pk>/<int:user_id>/', post_handler, name='post_handler')
]

social/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.
class User(AbstractUser):
	img = models.ImageField(upload_to='profile_photo/', blank=True)


class RequestFriends(models.Model):
	user_send = models.ForeignKey(User, related_name='send', on_delete=models.CASCADE)
	user_accept = models.ForeignKey(User, related_name='accept', on_delete=models.CASCADE)
	accepted = models.BooleanField(default=False)



class UserFriends(models.Model):
	owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE)
	friend = models.ForeignKey(User, related_name='friend', on_delete=models.CASCADE)


class ProfilePost(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	text = models.CharField(max_length=800)
	img = models.ImageField(upload_to='post_photo/', blank=True)
	pub_date = models.DateTimeField(default=timezone.now)


class LikesPost(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(ProfilePost, on_delete=models.CASCADE)


class Comment(models.Model):
	from_user = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(ProfilePost, on_delete=models.CASCADE)
	text = models.TextField()
	date = models.DateTimeField(default=timezone.now)

social/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User, ProfilePost

class RegistrationUser(UserCreationForm):

	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Имя'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Фамилия'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Логин'}))
	email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Электронная почта'}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Придумайте пароль'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Повторите пароль'}))

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginUser(AuthenticationForm):

	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-2 mr-sm-2'}))

	class Meta:
		model = User
		fields = ['username', 'password']


class EditUserInfo(UserChangeForm):
	
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'placeholder': 'Фамилия'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'readonly': True}))
	email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control mb-2 mr-sm-2', 'readonly': True}))
	img = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control', 'style': 'width: 350px;'}), required=False)


	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'img']
		

class CreatePostForm(forms.Form):


	user = forms.CharField(widget=forms.HiddenInput(attrs={'name': 'user_id', 'value': '{{user.id}}'}))
	text = forms.CharField(widget=forms.Textarea(attrs={
			'class': 'form-control',
			'cols': '46',
			'rows': '16',
			'placeholder': 'Максимальное кол-во символов 800. Для переноса строки используйте ENTER',
			'maxlength': '800',
			'style': 'resize: none;'
		}))
	img = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)

	class Meta:
		model = ProfilePost
		fields = ['text', 'img']

social/messanger/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from users.models import User
from .models import Chat, Message

# Create your views here.
class IndexView(TemplateView):
	template_name = 'messanger/index.html'


def chat_list(request):

	context = {}

	if request.method == 'GET':
		if 'add_new_chat' in request.GET:
				with_user = request.GET.get('with_user')

				if len(Chat.objects.filter(user_id=request.user.id).filter(with_user_id=with_user).all()) >= 1:
					context['error'] = 'Диалог с данным пользователем уже есть.'
				else:
					c = Chat(
						user = request.user,
						with_user = User.objects.get(pk=with_user)
					)
					c2 = Chat(
						user=User.objects.get(pk=with_user),
						with_user=request.user
					)
					c.save()
					c2.save()
					return HttpResponseRedirect(reverse('messanger:chats'))

		elif 'user' in request.GET and 'with_user' in request.GET:
			user = request.GET.get('user')
			with_user = request.GET.get('with_user')

			Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first().delete()
			Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first().delete()

			return HttpResponseRedirect(reverse('messanger:chats'))


	if len(Chat.objects.filter(user_id=request.user.id).all()) >= 1:
		context['chats'] = Chat.objects.filter(user_id=request.user.id).all()
		context['chats_with_id'] = []

		for chat in context['chats']:
			context['chats_with_id'].append(chat.with_user.id)

		print(context['chats_with_id'])

	else:
		context['chats'] = []

	return render(request, 'messanger/chat_list.html', context=context)


def chat_view(request, user, with_user):
	context = {}
	context['chat'] = Chat.objects.filter(user_id=user).filter(with_user_id=with_user).first()
	context['with_user_dialog'] = User.objects.get(pk=with_user)

	if request.method == 'POST':
		if 'msg_text' in request.POST:
			msg1 = Message(
				user=request.user,
				chat=context['chat'],
				text=request.POST.get('msg_text')
			)
			msg1.save()

			msg2 = Message(
				user=request.user,
				chat=Chat.objects.filter(user_id=with_user).filter(with_user_id=user).first(),
				text=request.POST.get('msg_text')
			)
			msg2.save()

	return render(request, 'messanger/chat.html', context=context)

social/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required

from .models import User, RequestFriends, UserFriends, ProfilePost, LikesPost, Comment
from .forms import *


# Create your views here.
class RegistrationView(CreateView):
	template_name = 'users/registration.html'
	model = User
	form_class = RegistrationUser


	def get_success_url(self):
		return reverse('messanger:index')


	def form_valid(self, form):
		user = form.save()
		login(self.request, user)
		return HttpResponseRedirect(reverse('messanger:index'))


class LoginUserView(LoginView):

	template_name = 'users/login.html'
	model = User
	form_class = LoginUser


	def get_success_url(self):
		return reverse('messanger:index')


def user_profile(request, pk):

	form = EditUserInfo(instance=request.user)
	form_create_post = CreatePostForm()

	context = {}

	if request.method == 'POST':
		if 'profile_change' in request.POST:
			form = EditUserInfo(data=request.POST, files=request.FILES, instance=request.user)
			if form.is_valid():			
				form.save()

		elif 'create_post' in request.POST:
			pp = ProfilePost(
				user=request.user,
				text=request.POST.get('text'),
				img=request.FILES.get('img')
			)
			pp.save()

		elif 'comment_text' in request.POST:
			c = Comment(
				from_user=request.user,
				post=ProfilePost.objects.get(pk=request.POST.get('post_id')),
				text=request.POST.get('comment_text')
			)
			c.save()


	if request.method == 'GET':

		if 'check_comment' in request.GET and len(Comment.objects.filter(post_id=request.GET.get('check_comment'))) >= 1:
			context['comment_list'] = Comment.objects.filter(post_id=request.GET.get('check_comment')).all()
			print(context['comment_list'])


	context['form'] = form
	context['form_create_post'] = form_create_post
	context['user_profile'] = User.objects.get(pk=pk)


	if pk != request.user.id:
		owner = request.user
		friend = User.objects.get(pk=pk)

		if len(RequestFriends.objects.filter(user_send_id=owner.id).filter(user_accept_id=friend.id).all())>=1:
			context['friend_status'] = 'request_sent'
		
		elif len(UserFriends.objects.filter(owner_id=owner.id).filter(friend_id=friend.id).all())>=1:
			context['friend_status'] = 'in_friendlist'

		else:
			context['friend_status'] = 'add_friend'


	if len(User.objects.get(pk=pk).profilepost_set.all())>=1:
		context['post_list'] = ProfilePost.objects.filter(user_id=pk).order_by('-pub_date').all()


	return render(request, 'users/profile.html', context=context)


def accept_friend(request, senter_id, accepter_id):

	request_friendlist = RequestFriends.objects.filter(
		user_send_id=senter_id
	).filter(
		user_accept_id=accepter_id
	).first()

	request_friendlist.accept = True

	owner = request_friendlist.user_send
	friend = request_friendlist.user_accept

	request_friendlist.delete()


	uf_for_user1 = UserFriends(owner = owner, friend = friend)
	uf_for_user2 = UserFriends(owner=friend, friend=owner)

	uf_for_user1.save()
	uf_for_user2.save()

	return HttpResponseRedirect(reverse('users:friend_list', kwargs={'pk':request.user.id}))


def reject_friend(request, senter_id, accepter_id):

	request_friendlist = RequestFriends.objects.filter(
		user_send_id=senter_id
	).filter(
		user_accept_id=accepter_id
	).delete()

	return HttpResponseRedirect(reverse('users:profile', kwargs={'pk':accepter_id}))


def create_request_friends(request, senter_id, accept_id):

	if request.user.id == senter_id:
		if len(RequestFriends.objects.filter(user_send_id=senter_id).filter(user_accept_id=accept_id))<1:
			request_to_friends = RequestFriends(
				user_send = request.user,
				user_accept = User.objects.get(pk=accept_id),
				accepted = False
			)
			request_to_friends.save()

	return HttpResponseRedirect(reverse('users:profile', kwargs={'pk':accept_id}))


def delete_friend(request, owner_id, friend_id):

	UserFriends.objects.filter(owner_id=owner_id).filter(friend_id=friend_id).delete()
	UserFriends.objects.filter(owner_id=friend_id).filter(friend_id=owner_id).delete()


	return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': friend_id}))


def check_friend_list(request, pk):

	context = {}

	if request.user.id == pk:

		if request.method == 'POST' and 'found_user' in request.POST:
			login_to_found = request.POST.get('found_user')
			try:
				context['found_user'] = User.objects.filter(username=login_to_found).first()
			except:
				context['found_user'] = 'Пользователь был не найден'

		return render(request, 'users/friend_list.html', context=context)

	return HttpResponseRedirect(reverse('messanger:index'))


def post_handler(request, pk, user_id):

	post = ProfilePost.objects.get(pk=pk)



	if request.method == 'GET':

		if request.GET.get('add_like'):

			if len(LikesPost.objects.filter(user_id=request.user.id).filter(post_id = post.id).all()) <= 1:
				lp = LikesPost(
					user = request.user,
					post = post
				)
				lp.save()

		elif request.GET.get('delete_like'):
			if len(LikesPost.objects.filter(user_id=request.user.id).filter(post_id = post.id).all()) >= 1:
				LikesPost.objects.filter(user_id=request.user.id).filter(post_id=post.id).first().delete()


		elif request.GET.get('delete_post'):
			if request.user.id == user_id:
				ProfilePost.objects.get(pk=pk).delete()


	return HttpResponseRedirect(reverse('users:profile', kwargs={'pk':post.user.id}))


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('users:login'))

social/users/templates/users/friend_list.html
{% extends 'base.html' %}
{% block content %}
	<div style="background: #DEF7FE;">
		<h1 style="padding: 10px;">Список ваших друзей</h1>
		<hr>
		<form style="margin-left: 5px;" method="post" action="{%url 'users:friend_list' user.id%}">
			{%csrf_token%}
			<input style="width: 250px; border-left: none; border-top: none; border-color: #DEF7FE; box-shadow: none;" class="" type="" name="found_user" placeholder="Введите логин пользователя"><input class=" btn-success" type="submit" name="" value="Найти" style="border:None; background: #DEF7FE; bor">
			
		</form>
		{%if found_user%}
		<hr>
			{%if found_user == 'Пользователь был не найден'%}
				<p style="font-size: 18px;">{{found_user}}</p>
			{%else%}
			<div style="padding: 10px;">
				{% if found_user.img %}
	        	<img src="{{ found_user.img.url }}" style="float: left;width: 100px; height: 120px;">
		        {%endif%}
		        	<p style="font-size: 18px; padding-right: 10px;">
		        			
		        			{{found_user.username}}<br>
		        			{{found_user.get_full_name}}<br>
		        			<a class="btn btn-outline-info" href="{% url 'users:profile' found_user.id %}" style="font-size: 14px;">Открыть профиль</a><br>
		        	</p>
		      </div>
			{%endif%}

		{% endif %}

		<hr>
		{% if user.accept.all %}
		{%for req in user.accept.all%}
            			
            		<p class="dropdown-item">
            			Запрос в друзья от {{req.user_send.username}}<br>
            			<a class="btn btn-outline-success" href="{% url 'users:accept_friend' req.user_send.id user.id%} ">Принять</a><a class='btn btn-outline-danger' href="{%url 'users:reject_friend' req.user_send.id user.id%}"> Отклонить</a>
            		</p>
            		
        {%endfor%}
        {%else%}
        <p>Заявок в друзья пока нет.</p>
        {% endif %}  <hr>
        {%for friend_in_list in user.owner.all%}
        <div style="padding: 10px;">
        	{%if friend_in_list.friend.img%}
        <img src="{{ friend_in_list.friend.img.url }}" style="float: left;width: 100px; height: 120px;">
	        {%endif%}
	        		<p style="font-size: 18px; padding-right: 10px;">
	        			
	        			{{friend_in_list.friend.username}}<br>
	        			{{friend_in_list.friend.get_full_name}}<br>
	        			<a class="btn btn-outline-info" href="{% url 'users:profile' friend_in_list.friend.id %}" style="font-size: 14px;">Открыть профиль</a><br>
	        			<a class="btn btn-outline-danger" style="font-size: 14px;" href="{% url 'users:delete_friend' user.id friend_in_list.friend.id%}">Удалить из друзей</a>
	        	</p>
	      </div>
	      <hr>
        {%endfor%}
      
        

	</div>
{%endblock%}

social/users/templates/users/login.html
{% extends 'reg_log_base.html' %}
{% block content %}

{% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 15px;">
                            <p style="list-style-type: none;">{{form.non_field_errors}}</p>
                        </div>
                        {% endif %}

	<form method="post" style="padding: 40px; background: #DEF7FE;">
	{%csrf_token%}
	<div class="d-flex justify-content-center">
  		<div class="p-2"><label for="{{form.username.id_for_label}}">Логин:</label>{{form.username}}</div>
  		<div class="p-2"><label for="{{form.password.id_for_label}}">Пароль:</label>{{form.password}}</div>
	</div>
	<div style="width: 100%; text-align: center;">
	<input type="submit" class='btn btn-outline-info' name="" value="Авторизоваться">
	</div>
</form>

{% endblock %}

social/users/templates/users/profile.html
{% extends 'base.html' %}
{% load user_id_filter %}
{% block content %}


<div style="background: #DEF7FE; padding-bottom: 50px;" class="container">
	<h2>
		{{user_profile.username}}  {%if user_profile.is_superuser%}<button class="btn btn-danger">Администратор</button>{%endif%}
		
		<div style="float: right; margin: 10px; font-size: 17px;">
			<p>{{user.last_login}}</p>	
		</div>
	</h2>
	<h5>
		{{user_profile.get_full_name}}		
	</h5>

	{% if user_profile.img %}
	<img src="{{ user_profile.img.url }}" style="width: 200px; height: 250px;">
	{%endif%}
		{% if user.id == user_profile.id %}
	{% if request.GET.edit_profile == 'yes' %}

	<form method="post" action="{% url 'users:profile' user.id %}" enctype="multipart/form-data">
		{%csrf_token%}
		<input type="hidden" name="profile_change">
		 <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.first_name.id_for_label}}">Имя</label>
                                                {{form.first_name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                                                {{form.last_name}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{form.username.id_for_label}}">Имя пользователя</label>
                                            {{form.username}}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{form.email.id_for_label}}">Адрес электронной
                                                почты</label>
                                            {{form.email}}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{form.img.id_for_label}}">Аватар</label>
                                            {{form.img}}
                                        </div>
                                    </div>
        <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-outline-info btn-block" type="submit" value="Изменить данные аккаунта">
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                            
							</div>
	</form><br>
	{% endif %}
	{% if request.GET.edit_profile == 'yes' %}
	<a href="{% url 'users:profile' user.id %}" class="btn btn-outline-danger btn-block">Отменить</a>
	
	{% else %}

		<div style="margin-top: 10px; font-size: 17px;">
			<a class="btn btn-outline-info" href="{% url 'users:profile' user.id %}?edit_profile=yes">Редактировать профиль</a>	
		</div>
	
	{% endif %}
	{% endif %}
	
	{% if user_profile.id != user.id %}
		
		{% if friend_status == 'in_friendlist' %}
			<div style="margin-top: 10px; font-size: 17px;">
				<p style='font-size: 18px; margin-bottom: 0px;'>Уже в друзьях</p>
			<a class="btn btn-outline-danger" href="{% url 'users:delete_friend' user.id user_profile.id%}">Удалить из друзей</a>	
		</div>
		{% elif friend_status == 'add_friend' %}
        	<div style="margin-top: 10px; font-size: 17px;">
				<a class="btn btn-outline-success" href='{% url "users:create_request_friends" user.id user_profile.id %}'>Добавить в друзья</a>
			</div>
		{% elif friend_status == 'request_sent' %}
			<div style="margin-top: 10px; font-size: 17px;">
				<p style='font-size: 18px; margin-bottom: 0px;'>Запрос отправлен</p>
				<a class="btn btn-outline-info" href='{%url "users:reject_friend" user.id user_profile.id%}'>Отклонить запрос</a>
			</div>
		{% endif %}

		<div style="margin-top: 10px; font-size: 17px;">
		<a class="btn btn-outline-info" href='{%url "messanger:chats"%}?add_new_chat=yes&with_user={{user_profile.id}}'>Начать диалог</a>
	</div>
	{% endif %}
	
	

	{%if user.id == user_profile.id%}


		<div id="zatemnenie">
      <div id="okno">
      	<a href="#" class="close" style="">❌</a>
        <h5>Создание поста.</h5>
        
        <form action='{% url "users:profile" user.id %}' enctype="multipart/form-data" method="post">
        	{% csrf_token %}
        	<input type="hidden" name="create_post">
        	{{form_create_post.user}}
        	{{form_create_post.text}}
        	<label style="margin-top: 20px;" for="{{form_create_post.img.id_for_label}}">Вы можете прикрепить одну фотографию к вашему посту.</label>
        	{{form_create_post.img}}
        	<input class="btn btn-outline-info" style="margin-top: 20px;" type="submit" name="" value="Создать">
        </form>

      </div>
    </div>



	<div style="text-align: center; margin-top: 20px;">
		<a class="btn btn-outline-info" style="font-size: 14px;" href="#zatemnenie">Создать пост</a>
	</div>
	{% endif %}

	{% for post in post_list %}
		
		<div id="{{post.id}}" class="d-flex" style="background: #B5F2EA; margin-top: 20px; border-radius: 10px;">
  		
  			{%if post.img%}
  		
  			<div class="p-2 flex-fill">
  				
				<img src="{{post.img.url}}" style="max-width: 500px; max-height: 500px; ">

  			</div>
  		
  			{% endif %}
  		
  			<div class="p-2 flex-fill">
  		
  				<div><p>{{post.text|linebreaksbr}}&nbsp;&nbsp;&nbsp;</p></div>
 
				<p style="text-align: right; margin-left: 10px; margin-right: 10px;">{{post.pub_date}}	 {%if user.id == user_profile.id%}<a style="font-size: 14px;text-align: right;" href="{% url 'users:post_handler' post.id user_profile.id %}?delete_post=yes" class="btn btn-outline-danger">Удалить публикацию</a>{%endif%}
					
					{% if post.likespost_set%}
						{%for like_in_post in post.likespost_set|id_filter:user.id%}
							{%if like_in_post.post.id == post.id and like_in_post.user.id == user.id%}
					 			<a href="{% url 'users:post_handler' post.id user_profile.id %}?delete_like=yes#{{post.id}}" style="text-decoration: none; font-size: 27px;">&nbsp;❤️</a>
					 			<p style="text-align: right;">Лайков всего - {{ post.likespost_set.all|length }}</p>
				 			{%elif forloop.last and like_in_post.user.id != user.id %}
					 			<a style="font-size: 30px; text-decoration: none; " href="{% url 'users:post_handler' post.id user_profile.id %}?add_like=yes#{{post.id}}">&nbsp;♡</a>
					 			<p style="text-align: right;">Лайков всего - {{ post.likespost_set.all|length }}</p>
				 			{%endif%}
				 			{%if post.comment_set%}
				 				<a href="{%url 'users:profile' user_profile.id%}?check_comment={{post.id}}">Посмотреть комментарии</a>
				 			{%endif%}
				 			{% if comment_list %}
				 			<br>
				 				{% for comment in comment_list %}
				 					{{comment.text}} | {{comment.date}} | {{comment.from_user.username}}<br>
				 				{% endfor %}
				 			{% endif %}
				 			<form style="max-width: 400px;" method="post" action="{% url 'users:profile' user_profile.id %}">
				 				{%csrf_token%}
					 			<input type="hidden" value="{{post.id}}" name="post_id">
					 			<input type="text" class="form-control" name="comment_text"><input class="btn btn-outline-success" type="submit" name="">
					 		</form>
				 		{%empty%}
					 		<a style="font-size: 30px; text-decoration: none; " href="{% url 'users:post_handler' post.id user_profile.id %}?add_like=yes#{{post.id}}">&nbsp;♡</a>
					 		<br>
					 		<p style="text-align: right;">Лайков всего - {{ post.likespost_set.all|length }}</p>
				 		{%endfor%}
					{%endif%}
					</p>
		
			</div>
		
		</div>
		
	{%endfor%}

</div>

{% endblock %}

social/users/templates/users/registration.html
{%extends 'reg_log_base.html'%}
{% block content %}

{% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            <p style="list-style-type: none;">{{form.as_text}}</p>

                        </div>
                        {% endif %}

<form method="post" style="padding: 40px; background: #DEF7FE;">
	{%csrf_token%}
	<div class="d-flex justify-content-center">
  		<div class="p-2"><label for="{{form.first_name.id_for_label}}">Имя:</label>{{form.first_name}}</div>
  		<div class="p-2"><label for="{{form.last_name.id_for_label}}">Фамилия:</label>{{form.last_name}}</div>
	</div>
	<div class="d-flex justify-content-center">
  		<div class="p-2"><label for="{{form.username.id_for_label}}">Придумайте логин:</label>{{form.username}}</div>
  		<div class="p-2"><label for="{{form.email.id_for_label}}">Электронная почта:</label>{{form.email}}</div>
	</div>
	<div class="d-flex justify-content-center">
  		<div class="p-2"><label for="{{form.password1.id_for_label}}">Придумайте пароль:</label>{{form.password1}}</div>
  		<div class="p-2"><label for="{{form.password2.id_for_label}}">Повторите пароль:</label>{{form.password2}}</div>
	</div>
	<div style="width: 100%; text-align: center;">
	<input type="submit" class='btn btn-outline-info' name="" value="Зарегистрироваться">
	</div>
</form>



{% endblock %}